In [2]:
import torch
from scipy import linalg

/home/gergo/.local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
n = 10

In [4]:
A = torch.rand(n, n)
A = torch.matmul(A, torch.transpose(A, 0, 1))
A

tensor([[4.7070, 3.0368, 2.0501, 2.6538, 4.2286, 4.6933, 3.5773, 3.1712, 3.6083,
         4.1027],
        [3.0368, 3.0257, 1.3360, 1.8696, 3.3739, 3.3890, 2.3868, 2.3752, 2.7235,
         2.9370],
        [2.0501, 1.3360, 1.4516, 1.2106, 1.9884, 2.2206, 1.2493, 1.4858, 1.4559,
         1.3992],
        [2.6538, 1.8696, 1.2106, 2.0935, 2.6729, 2.9737, 1.8244, 2.1128, 2.2167,
         2.6367],
        [4.2286, 3.3739, 1.9884, 2.6729, 4.8589, 4.3680, 3.2838, 3.4792, 3.6747,
         4.1584],
        [4.6933, 3.3890, 2.2206, 2.9737, 4.3680, 5.3836, 3.6690, 3.3377, 3.8078,
         4.3501],
        [3.5773, 2.3868, 1.2493, 1.8244, 3.2838, 3.6690, 3.4327, 2.4550, 3.1159,
         3.7747],
        [3.1712, 2.3752, 1.4858, 2.1128, 3.4792, 3.3377, 2.4550, 3.0967, 2.9360,
         3.4142],
        [3.6083, 2.7235, 1.4559, 2.2167, 3.6747, 3.8078, 3.1159, 2.9360, 4.1917,
         4.0746],
        [4.1027, 2.9370, 1.3992, 2.6367, 4.1584, 4.3501, 3.7747, 3.4142, 4.0746,
         4.8668]])

In [5]:
evals, evecs = torch.linalg.eigh(A)

In [6]:
evals

tensor([1.6088e-03, 4.9953e-02, 2.1735e-01, 3.2218e-01, 6.1596e-01, 6.7244e-01,
        8.4980e-01, 1.1914e+00, 1.7715e+00, 3.1416e+01])

In [7]:
class from_evecs:

    def __init__(self, n, f, evals, evecs):
        self.n = n
        self.f = f
        self.evals = evals
        self.evecs = torch.transpose(evecs, 0, 1)
    
    def __call__(self, t = 1):
        sum = torch.eye(self.n, self.n)
        for i in range(self.n):
            sum += (self.f(t, self.evals[i]) - 1) * torch.outer(self.evecs[i], self.evecs[i])

        return sum

In [8]:
continous = from_evecs(10, lambda t, x: x ** t, evals, evecs)

In [9]:
l = [continous(float(i)/10) for i in range(10)]
dif = list(map(
    lambda x: torch.sum(torch.mul(x, x)),
    iter([l[i+1] - l[i] for i in range(9)])
    ))

In [10]:
dif

[tensor(0.5008),
 tensor(0.4684),
 tensor(0.7364),
 tensor(1.3785),
 tensor(2.6978),
 tensor(5.3435),
 tensor(10.6239),
 tensor(21.1503),
 tensor(42.1283)]

In [21]:
B = torch.rand(n, n)
B = 0.5 * (B + torch.transpose(B, 0, 1)) #Make B symmetric to ensure real eigenvalues
B

tensor([[0.6844, 0.7816, 0.5170, 0.4198, 0.4086, 0.3769, 0.3312, 0.3246, 0.6116,
         0.5388],
        [0.7816, 0.9417, 0.3540, 0.6782, 0.5304, 0.4007, 0.6198, 0.5983, 0.6827,
         0.1853],
        [0.5170, 0.3540, 0.0360, 0.2320, 0.5782, 0.5626, 0.4022, 0.6020, 0.7561,
         0.1121],
        [0.4198, 0.6782, 0.2320, 0.9429, 0.6062, 0.3670, 0.2311, 0.8202, 0.5063,
         0.2495],
        [0.4086, 0.5304, 0.5782, 0.6062, 0.4176, 0.2129, 0.8638, 0.5840, 0.4110,
         0.1900],
        [0.3769, 0.4007, 0.5626, 0.3670, 0.2129, 0.0781, 0.6300, 0.2620, 0.2318,
         0.5731],
        [0.3312, 0.6198, 0.4022, 0.2311, 0.8638, 0.6300, 0.2339, 0.6016, 0.4375,
         0.1265],
        [0.3246, 0.5983, 0.6020, 0.8202, 0.5840, 0.2620, 0.6016, 0.2780, 0.7969,
         0.6354],
        [0.6116, 0.6827, 0.7561, 0.5063, 0.4110, 0.2318, 0.4375, 0.7969, 0.2403,
         0.3346],
        [0.5388, 0.1853, 0.1121, 0.2495, 0.1900, 0.5731, 0.1265, 0.6354, 0.3346,
         0.9680]])

In [22]:
evals, evecs = torch.linalg.eig(B)

In [23]:
evals

tensor([ 4.8331e+00+0.j, -1.0794e+00+0.j,  1.0233e+00+0.j, -7.0753e-01+0.j,
        -5.4662e-01+0.j,  6.3902e-01+0.j,  5.3702e-01+0.j,  1.9041e-01+0.j,
         7.3563e-04+0.j, -6.9211e-02+0.j])

In [ ]:
"""
    v                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
"""